CelestiaProject/CelestiaContent

- data/nearstars.stc
Changes include:
- Fixed orbit orientations so they match radial velocity data
- Updated orbits for a few systems
- Fixed coordinates and names for a few stars
> Update of nearstars.stc

- data/nearstars.stc
- data/revised.stc
- data/starnames.dat
Some things that were forgotten in #25...
> Fix Del Sgr distance; update Alf Cen names for consistency with IAU

- README
see https://github.com/CelestiaProject/Celestia/pull/831 for more info
> update ambiguous licensing

- data/revised.stc
v1.0.4, hopefully final version
see also [Celestia#888](https://github.com/CelestiaProject/Celestia/pull/888)
> Update star database (again)

- data/CMakeLists.txt
- data/nearstars.stc
See [Celestia#915](https://github.com/CelestiaProject/Celestia/pull/915)
> Some fixes to nearstars.stc + remove stars.txt

- data/well-known-dsonames.txt
- data/well-known-starnames.txt
Generated by parsing
1. starnames.dat/galaxies.dsc/openclusters.dsc/globulars.dsc
2. https://github.com/Stellarium/stellarium/blob/master/po/stellarium-skycultures/stellarium-skycultures.pot .
Finding the ones shared in both and combined to become these lists.
> Add lists of well known star names and dso names for localization

- data/extrasolar.ssc
- data/extrasolar.stc
Change log: https://celestia.space/forum/viewtopic.php?p=156580#p156580
> February 2022 exoplanet update

- data/extrasolar.ssc
- data/extrasolar.stc
Change log: https://celestia.space/forum/viewtopic.php?p=157130#p157130
> April 2022 exoplanet update

- data/minormoons.ssc
- data/nearstars.stc
Added new names of Saturn's moons; updated Gliese 896.
Would it be possible for me to be added back to the CelestiaProject group so I can merge PRs myself again...? I stupidly left it but I'm still contributing occasionally...
> Some updates

- data/asterisms.dat
* "Star Lac" seems likely to be HIP 109754, which has neither a Bayer nor a Flamsteed designation despite being the fifth (?) brightest star in Lacerta
* "K Pup" seems likely to be k1 Puppis (Bayer designation not included in starnames.dat)
* "Rho Vel" appears to be a misreading of "p Vel"
> Fix asterisms.dat loading errors

- data/nearstars.stc
- Added temperature, radius, and rotation parameters for Ran (Epsilon Eridani)
- Added radius (forgot to cite (Teixeira et al. 2009)) and rotation period for Tau Ceti
> Minor update to nearstars.stc

- data/world-capitals.ssc
- po/ar.po
- po/be.po
- po/bg.po
- po/celestia-data.pot
- po/de.po
- po/el.po
- po/en.po
- po/es.po
- po/fr.po
- po/gl.po
- po/hu.po
- po/it.po
- po/ja.po
- po/ko.po
- po/lt.po
- po/lv.po
- po/nb.po
- po/nl.po
- po/pl.po
- po/pt.po
- po/pt_BR.po
- po/ro.po
- po/ru.po
- po/sk.po
- po/sv.po
- po/tr.po
- po/uk.po
- po/zh_CN.po
- po/zh_TW.po
It was changed back in September 2022
> Change Nur-Sultan to Astana

- data/asterisms.dat
Also replace Latin Bayer designations with HIP identifiers
> [asterisms] Standardise Bayer designations to Celestia format

- data/dwarfplanets.ssc
- data/solarsys.ssc
Data from the NASA factsheets at https://nssdc.gsfc.nasa.gov/planetary/factsheet/
> Add masses for the major planets, Pluto and the Moon

- data/nearstars.stc
Populated using a script:
1. collect all names
2. query the name in wikipedia to see if a page is available
3. get the canonical link to use in nearstars.stc
> Populate InfoURL for nearstars.stc

- LICENSES/CC0-1.0.txt
- textures/lores/haumea-rings.png.license
* Per discussion on Celestia discord "I assign it to be public domain" (@Askaniy)
* Per REUSE documentation, use the CC0 license for this case
> Annotate haumea-rings.png as CC0-1.0

- README
- models/arrokoth.cmod.license
> Add CC0 license to arrokoth.cmod

- extras-standard/shroxmars/models/marsglobalsurvr.3ds.license
- extras-standard/shroxmars/models/marsodyssey.3ds.license
See CelestiaProject/Celestia#831
> Add CC-BY-4.0 license to shroxmars models per discussion at #831

- data/asteroids.ssc
Not actually named after Celestia Project, but this is still our mascot asteroid regardless.
> 1252 Celestia

- README
- textures/hires/mstar.jpg.license
- textures/lores/mstar.jpg.license
- textures/medres/mstar.jpg.license
Re-raising #156 to resolve conflicts
> License annotation for M-type star texture

- LICENSES/JPL-image.txt
- models-extra/bacchus.3ds.license
- models-extra/castalia.3ds.license
- models-extra/geographos.3ds.license
- models-extra/golevka.3ds.license
- models-extra/ky26.3ds.license
- models-extra/toutatis.3ds.license
- models/bacchus.cmod.license
- models/castalia.cmod.license
- models/geographos.cmod.license
- models/golevka.cmod.license
- models/ky26.cmod.license
- models/toutatis.cmod.license
See discussion on #162 for details
> Add JPL-image license to Scott Hudson models

- extras-standard/apollo/apollo.ssc
Identical to #182, but this time to the Apollo lunar missions 10 to 17
> Add COSPAR ID to the Apollo 10 to 17 missions

- extras-standard/shroxclassic/shroxclassic.ssc
Similar to #182 and #183, this time to all orbital missions of ***Project Mercury*** (1962-1963) and ***Project Gemini*** (1964-1966)
> Add COSPAR ID to Mercury and Gemini (shroxclassic.ssc)

- extras-standard/mir/mir.ssc
Revision of #185. Applied the UTC-to-TDB conversion of the dates written by @pedro-fixingstuff
> Refine Launch/Reentry Dates for Mir (2nd Attempt)

- data/pulsars.stc
> Update pulsar catalog

- data/nearstars.stc
- Define B component as a binary, with full orbital elements
- Parameter updates for the primary star
> Update Gliese 229

- textures/hires/ganymede.jpg.license
- textures/hires/jupiter.jpg.license
- textures/hires/neptune.jpg.license
- textures/hires/phobos.jpg.license
- textures/hires/saturn.jpg.license
- textures/hires/triton.jpg.license
- textures/hires/uranus.jpg.license
- textures/lores/ganymede.jpg.license
- textures/lores/jupiter.jpg.license
- textures/lores/neptune.jpg.license
- textures/lores/phobos.jpg.license
- textures/lores/puck.jpg.license
- textures/lores/saturn.jpg.license
- textures/lores/triton.jpg.license
- textures/lores/uranus.jpg.license
- textures/medres/ganymede.jpg.license
- textures/medres/jupiter.jpg.license
- textures/medres/neptune.jpg.license
- textures/medres/phobos.jpg.license
- textures/medres/puck.jpg.license
- textures/medres/saturn.jpg.license
- textures/medres/triton.jpg.license
- textures/medres/uranus.jpg.license
Most of my textures were switched from CC-BY-SA to CC-BY.
Also indicated that Uranus hasn't free license.
> Update licenses to my textures

- data/extrasolar.ssc
- data/extrasolar.stc
- Update to latest version of exoplanets catalog
- Fixes parser warnings about radius definition on barycenters
> Exoplanets November update

- CMakeLists.txt
> Set CMP0177 policy

- data/visualbins.stc
Source: Eggleton et al. (2008) https://cdsarc.cds.unistra.fr/viz-bin/cat/J/MNRAS/389/869
> Fix invalid spectral type on CHI1 Hya B

- data/galaxies.dsc
Source Karachentsev et al. (2018), de Velacours type T=10 (dwarf irregular)
> Add morphological type to ESO 294-10

- CMakeLists.txt
- cmake/ResizeImage.cmake
- textures/CMakeLists.txt
> Preserve RGB channels when resizing transparent PNGs

- data/comets.ssc
- data/dwarfplanets.ssc
- data/outersys.ssc
- data/solarsys.ssc
- comets.ssc: Style change to align with other files
- dwarfplanets.ssc and outersys.ssc: True colour updates
> Solar System update (2025-05-25)

- data/comets.ssc
Based on rotation periods defined by [Knight (2023)](https://arxiv.org/abs/2304.09309)
> Revised rotation periods for Giacobini–Zinner, Hale–Bopp, and Siding Spring

- data/comets.ssc
Nucleus radii by [Liu (2025)](https://www.aanda.org/articles/aa/full_html/2025/06/aa54632-25/aa54632-25.html) and rotation period by [Moreno (2025)](https://arxiv.org/abs/2504.01845)
> Physical characteristics for Tsuchinshan–ATLAS (2025)

- data/nearstars.stc
> Add SPDX headers to nearstars.stc
