data/nearstars.stc
data/outersys.ssc

Fixed:
- G 141-36 standardized to Giclas 141-36
- Mass ratios with Jupiter masses now mark both with a J to prevent confusion
- Remove extraneous parenthesis from 2001 KX76

Miscellaneous typo fix

---

data/extrasolar.stc

Apparently several planet-hosting pulsars had incorrect (far too cool) temperatures. This issue needs to be fixed, especially if there aren't going to be full updates to the default exoplanet catalog in the near future.

Remove incorrect pulsar temperatures

---

data/asterisms.dat

The line should go through the star s Eri, not S Eri. Since name lookup is currently case-sensitive, use the HIP id instead to specify the star.
Fixes #94

Fix constellation line in Eridanus

---

data/nearstars.stc

Source: Golovin et al. (2022) "The Fifth Catalogue of Nearby Stars" https://dc.g-vo.org/CNS5
Two tricky cases:
* WISE 1540-5101 appears to be duplicated as GJ 12258 and GJ 12259, I have used both identifiers
* LTT 1445 is listed as one entry GJ 3193 for the entire system, the name GJ 3192 does not appear in CNS5. I have therefore moved the name GJ 3193 from LTT 1445 A to the system barycenter

Additional GJ designations from CNS5

---

data/dwarfplanets.ssc

Use the Dawn Final model from https://sbnarchive.psi.edu/pds3/dawn/fc/DWNCSPC_4_01/DOCUMENT/CERES_COORD_SYS_180628.HTM
Fixes the position of the meridian at J2000, which should be RA 12h 51m, Dec 3.67°

Update Ceres rotation elements

---

data/nearstars.stc

This is an attempt to fix the star orbits' radial orientation issue as reported by Issue #92: Reversed binaries in nearstars.stc.
Star systems fixed are:
- Luhman 16 (Mean Anomaly error)
- Sirius (mirrored inclination)
- Gliese 234 (mirrored inclination, eccentricity update 0.38 -> 0.382)
- Gliese 229 (mirrored inclination)
The current orientation of Gliese 65 appears to be correct (Gliese 65 B is receding relative to Gliese 65 A), and the change is left out.

Fixing star orbits (issue #92)

---

data/globulars.dsc
data/openclusters.dsc

My first content PR, it completely rewrites the star cluster dsc files to remove dependency on ancient, undocumented Fridger scripts.
I've also adopted a newer, much more complete source for open star clusters and replaced mu25 isophote globular cluster radii to tidal radii ("Radius" in GCs are purely visual and only say the markers where to put thenselves). Sources are noted in the headers.
galaxies.dsc is left for a separate PR due to its making having a complexity on its own.
Any updates after this can be done by hand, without usage of scripts, due to the lack of dependence on the aformentioned scripts by Fridger.
Cheers!

Update globular and open cluster catalog

---

po/en.po

Also replace "Goat-Fish" with "Sea Goat" for Capricornus

[en] Remove incorrect fuzzy translations

---

data/solarsys.ssc

See Issue #128 
Modified:
- Earth (clouds stopped and now stays where they should be relative to the surface)
- Mars (same as Earth's case)
- Titan (180 degrees/day = 2 days rotation period form ~100 m/s wind speed at high altitudes)
- Venus (added a note explaining the 90 degrees/day rotation of the clouds.

CloudSpeed update

---

data/outersys.ssc

Updated colors of most objects in outersys.ssc to reflect their actual albedo, following the addition of color-calibrated asteroid texture. The four consensus dwarf planets are also now given the dwarfplanet class, but remains in outersys.ssc for the moment.

outersys.ssc color update

---

data/dwarfplanets.ssc
data/outersys.ssc

See Issue #129, going with making relatively large satellites use their physical classes (so Charon is a dwarfplanet and Vanth is an asteroid).

Standardize 'moon' vs 'minormoon' classification

---

.github/workflows/translations.yml

- Fixes warning in workflow output
- Also update checkout to v4

Use apt-get instead of apt in translations workflow

---

data/dwarfplanets.ssc

- Added albedo-adjusted color for the moon of Eris as well as updating its albedo and radius.
- Rotation of the system now uses Equatorial coordinates consistent with how the orbit of the moon is defined.

Eris system tinkering

---

.github/workflows/licenses.yml

The version of reuse in the Ubuntu-22.04 repositories lists JPL-image as a bad license. This would likely cause problems here. Install it via pipx instead.

Use pipx to install reuse

---

data/dwarfplanets.ssc
data/outersys.ssc

This pull request primarily focuses on updating orbits of satellites of objects in dwarfplanets.ssc and outersys.ssc, though it also contains new sources for existing info, polishes, and so on.

Satellite orbit and rotation

---

data/outersys.ssc

This commit adds 2 new trans-Neptunian objects: 2003 AZ84 and 2013 FY27. Both are some of the largest known objects orbiting beyond Neptune.
- 2003 AZ84 uses a hydrostatic equilibrium triaxial ellipsoid shape solution, with its meridian position referencing the 2014 occultation.
- Lacking rotational information, 2013 FY27 is given a placeholder rotation period of 9 hours, the average rotation period of TNOs. The reference source is mentioned in comments in outersys.ssc, and is also implemented for two other objects with no rotation periods: Albion and 2004 XR190.
- Both objects have satellite detections, but 2003 AZ84's satellite is lost while 2013 FY27's satellite does not have public solution; as such, neither are included in this commit.

2003 AZ84 and 2013 FY27

---

.github/workflows/checks.yml
checks/checkunicode.py

Verify that all our strings are normalized to NFC

Add check for Unicode normalization

---

data/minormoons.ssc
data/solarsys.ssc

Source: https://arxiv.org/abs/2401.04634
Also the Moon's LunarLambert is apparently 1 now, which is realistic, although I'd agree it is out of place, and I'm willing to revert it back to 0.5 for now to update it back later along with other known values

Uranus system mass/density update (and Moon LunarLambert apparently)

---

extras-standard/apollo/apollo.ssc
extras-standard/apollo/models/apollo.3ds.license
extras-standard/shroxclassic/models/gemini.3ds.license
extras-standard/shroxclassic/models/mercury7.3ds.license
extras-standard/shroxclassic/shroxclassic.ssc
extras-standard/shroxmars/shroxmars.ssc
extras-standard/skylab/models/skylab.3ds.license
extras-standard/skylab/skylab.ssc

Unlike shroxmars which was discussed as being under CC-BY-4.0, the other Shrox add-ons do not have a clear licensing situation.
Related issue: #144

Add licenses to apollo, shroxclassic, skylab add-ons

---

extras-standard/skylab/skylab.ssc

COSPAR ID added as an alternate name for Skylab

Add COSPAR ID to Skylab

---

data/dwarfplanets.ssc
data/solarsys.ssc

As a result of https://celestiaproject.space/forum/viewtopic.php?f=4&t=24482, I have changed the classifications of small moons around planetary bodies: Mars, Haumea, Makemake, Gonggong, and Quaoar, from minormoon to moon, providing that the system does not also contain much larger moons (as is the case for Pluto-Charon system). Considering this old discussion https://celestiaproject.space/forum/viewtopic.php?f=2&t=12329&start=20, this does not apply to asteroids.

Recategorization of minormoons around planetary bodies

---

models/elektra.cmod.license
models/eugenia.cmod.license
models/hygiea.cmod.license
models/interamnia.cmod.license
models/iris.cmod.license
models/juno.cmod.license
models/kleopatra.cmod.license
models/pallas.cmod.license
models/sylvia.cmod.license

More progress towards #162
From discussion there, source for these was [Vernazza et al. (2021)](https://www.aanda.org/articles/aa/full_html/2021/10/aa41781-21/aa41781-21.html), so CC-BY-4.0.

Add licenses for asteroid models from Vernazza et al. (2021)

---

data/charm2.stc

Some stars in charm2.stc are now defined elsewhere as barycenters, so setting radii does not make sense.

Disable some charm2 stars that are now barycenters

---

data/dwarfplanets.ssc
data/outersys.ssc

- Updated colors of Ixion and Quaoar using traced spectra from Marchi et al. (2003), and Makemake using processed spectrum from Alvarez-Candal et al. (2020).
- Removed Gonggong's oblateness, which is based on outdated data (reported by pedroJ)
- Removed Bond albedo values from Verbiscer et al. (2022), which are actually spherical albedo.
- Updated info links of Gonggong, Quaoar, and Sedna to reflect the changed Wikipedia article names.

2024-06-17 dwarfplanets / outersys update

---

data/nearstars.stc

Orbit now matches the plane-of-sky projection given in the original source. Radial velocities seem to be correct, comparing with another source not cited here.

Fix Luhman 16 orbit

---

data/comets.ssc
data/outersys.ssc
extras-standard/interstellar-objects/interstellar-objects.ssc

I have noticed that the last time ```comets.ssc``` was updated, it was over 16 years ago by Chris Laurel himself (https://github.com/CelestiaProject/CelestiaContent/commit/722fd82c1c9a9f93f8f24d2103ff17b942b6460d). But this only includes 4 comets:
- 1P/Halley
- 19P/Borrelly
- 153P/Ikeya–Zhang
- C/1995 O1 (Hale–Bopp)
This PR adds over 19 comets, mostly notable ones, to the main catalog for Celestia. These are the following:
- 2P/Encke
- 17P/Holmes
- 21P/Giacobini–Zinner
- 26P/Grigg–Skjellerup
- 29P/Schwassmann–Wachmann
- 46P/Wirtanen
- 55P/Tempel–Tuttle
- 96P/Machholz
- 109P/Swift–Tuttle
- 167P/CINEOS
- C/1956 R1 (Arend–Roland)
- C/1973 E1 (Kohoutek)
- C/1983 H1 (IRAS–Araki–Alcock)
- C/1996 B2 (Hyakutake)
- C/2006 P1 (McNaught)
- C/2013 A1 (Siding Spring)
- C/2014 UN271 …

Additional comets for Celestia (2025)

---

data/comets.ssc

Thanks to @AstroChara for spotting some erroneous values inputted on the radii of some comets. Counter-checked the values with those of JPL-SBDB and other journals wherever available.
- Both 2P/Encke and 19P/Borrelly are 4.8 km in diameter. Previously written incorrectly as ```# D = 4.2 km```
- C/1983 H1 is 9.2 km in diameter. Therefore, the correct radius value is 4.6 km, not 4.2 km
- Hale-Bopp's diameter was accidentally set equal to its radius (30 km) when its real value is actually ```# D = 60 km```
This acts as a patch update for PR #229

Minor corrections to radii/diameters of comets

---

data/nearstars.stc

Major data update for nearstars.stc.
This first commit contains updated data from Sol to Epsilon Eridani.
- Radius and temperatures are complete for stars with empirical measurements.
- Rotational elements are incomplete thus far; some stars have measured Inclination, but without AscendingNode; these entries have Inclination and AscendingNode field in, both set to 0.

nearstars.stc update (2025-02-09)

---

data/outersys.ssc

The TNO was given its official MPC name yesterday (2025-Jun-9)

Rename (307261) 2002 MS₄ to 307261 Máni

---

data/dwarfplanets.ssc
data/outersys.ssc

Updates the orbits with definitions relative to the Solar System Barycenter (SSB) at the J2000 epoch, queried from the Horizons system. These tend to be more stable over time than heliocentric orbits, as exemplified by [this footnote](https://en.wikipedia.org/wiki/Sedna_(dwarf_planet)#cite_note-footnoteG-6) to the Wikipedia article about Sedna.
The only exceptions are the Pluto system (reverted to heliocentric) and Arrokoth, as spacecraft trajectories are usually defined in a heliocentric frame, and thus using barycentric orbits might make the New Horizons encounters less accurate.

Use barycentric orbits for most centaurs and TNOs

---

data/dwarfplanets.ssc
data/outersys.ssc

Haumea (+Hi'iaka and Namaka), Quaoar (+Weywot), Ixion, Huya, Lempo-Hiisi-Paha and Achlys are updated with data from recent sources.
Spherical (Bond) albedos from [Verbiscer et al. (2022)](https://iopscience.iop.org/article/10.3847/PSJ/ac63a6) have been added to other objects, and the rotations of satellites have been set to either tidal lock or reasonable guesses for non-synchronous rotation. Provisional designations for satellites were removed if not assigned by the IAU, using [Johnston's Archive](https://www.johnstonsarchive.net/astro/binastnames.html) as a reference.
Rotational parameters of Haumea are taken from an add-on by n3.

Updates to TNO systems
